/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personality.analyst;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class favorites extends javax.swing.JFrame {

    /**
     * Creates new form zak_adm
     */
    public favorites() {
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("try.png"));
        Image img = icon.getImage().getScaledInstance(fav_pic.getWidth()-5, fav_pic.getHeight()-5, Image.SCALE_SMOOTH);
        fav_pic.setIcon(new ImageIcon(img));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fav_pic = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vibgyor_combo = new javax.swing.JComboBox();
        BACK = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        submit_but1 = new javax.swing.JButton();
        num_combo = new javax.swing.JComboBox();
        alp_combo = new javax.swing.JComboBox();
        food_combo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.blue);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INTERESTING SELECTIONS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select any color from VIBGYOR");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select any alphabet from A - G ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Select any taste for food");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Select any number from 1 - 7");

        vibgyor_combo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vibgyor_combo.setForeground(new java.awt.Color(51, 51, 51));
        vibgyor_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "Violet", "Indigo", "Blue", "Green", "Yellow", "Orange", "Red" }));
        vibgyor_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibgyor_comboActionPerformed(evt);
            }
        });

        BACK.setBackground(new java.awt.Color(255, 255, 255));
        BACK.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        BACK.setForeground(java.awt.Color.blue);
        BACK.setText("< BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jButton4.setForeground(java.awt.Color.blue);
        jButton4.setText("<<< BACK TO HOMEPAGE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        submit_but1.setBackground(new java.awt.Color(255, 255, 255));
        submit_but1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        submit_but1.setForeground(java.awt.Color.blue);
        submit_but1.setText("SUBMIT");
        submit_but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_but1ActionPerformed(evt);
            }
        });

        num_combo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        num_combo.setForeground(new java.awt.Color(51, 51, 51));
        num_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "01", "02", "03", "04", "05", "06", "07" }));
        num_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_comboActionPerformed(evt);
            }
        });

        alp_combo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        alp_combo.setForeground(new java.awt.Color(51, 51, 51));
        alp_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "A", "B", "C", "D", "E", "F", "G" }));
        alp_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alp_comboActionPerformed(evt);
            }
        });

        food_combo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        food_combo.setForeground(new java.awt.Color(51, 51, 51));
        food_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "Continental", "Chinese", "Labanese", "Fast food", "Mexican", "Italian", "Desi", " " }));
        food_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food_comboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fav_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(alp_combo, 0, 264, Short.MAX_VALUE)
                                .addComponent(vibgyor_combo, 0, 264, Short.MAX_VALUE)
                                .addComponent(food_combo, 0, 264, Short.MAX_VALUE)
                                .addComponent(num_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(submit_but1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addContainerGap(494, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(vibgyor_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(alp_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(food_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(num_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(fav_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit_but1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vibgyor_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibgyor_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vibgyor_comboActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
              you_basic u= new you_basic();        // TODO add your handling code here:
        setVisible(false);
       
u.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BACKActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       welcome w= new welcome();        // TODO add your handling code here:
        setVisible(false);
       
w.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void submit_but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_but1ActionPerformed
setVisible(false);
        
        String food=(String) food_combo.getSelectedItem();
 String col=(String) vibgyor_combo.getSelectedItem();   
 String alp= (String) alp_combo.getSelectedItem();
        
        if(food.equals("Continental") || col.equals("Violet") || alp.equals("A") )
	{
	new third("YOU ARE ABLE AND ACTIVE").setVisible(true);
	}
        else if(food.equals("Chinese") || col.equals("Indigo") || alp.equals("B"))
        {
        new third("YOU ARE BELOVED AND BOLD").setVisible(true);    
        }// TODO add your handling code here:
        else if(food.equals("Labanese") || col.equals("Blue") || alp.equals("C"))
        {
        new third("YOU ARE CALM AND CAREFUL").setVisible(true);    
        }
        else if(food.equals("Fast food ") || col.equals("Green") || alp.equals("D"))
        {
        new third("YOU ARE DARING AND DAZZLING").setVisible(true);    
        }
        else if(food.equals("Mexican") || col.equals("Yellow") || alp.equals("E"))
        {
        new third("YOU ARE ENCHANTING AND ENERGETIC").setVisible(true);    
        }
        else if(food.equals("Italian") || col.equals("Orange") || alp.equals("F"))
        {
        new third("YOU ARE FABULOUS AND FAITHFUL").setVisible(true);    
        }
        else if(food.equals("Desi") || col.equals("Red") || alp.equals("G"))
        {
        new third("YOU ARE GIFTED AND GENEROUS").setVisible(true);    
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_submit_but1ActionPerformed

    private void num_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_comboActionPerformed

    private void alp_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alp_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alp_comboActionPerformed

    private void food_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_food_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(favorites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(favorites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(favorites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(favorites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new favorites().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JComboBox alp_combo;
    private javax.swing.JLabel fav_pic;
    private javax.swing.JComboBox food_combo;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox num_combo;
    private javax.swing.JButton submit_but1;
    private javax.swing.JComboBox vibgyor_combo;
    // End of variables declaration//GEN-END:variables
}
