/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personality.analyst;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class you_basic extends javax.swing.JFrame {

    /**
     * Creates new form zak_adm
     */
    public you_basic() {
        initComponents();
       this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        ImageIcon icon = new ImageIcon(getClass().getResource("info1.jpg"));
        Image img = icon.getImage().getScaledInstance(info_pic.getWidth()-5, info_pic.getHeight()-5, Image.SCALE_SMOOTH);
        info_pic.setIcon(new ImageIcon(img));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        info_pic = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MOB_combo = new javax.swing.JComboBox();
        DOB_combo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        middle_name = new javax.swing.JTextField();
        last_name = new javax.swing.JTextField();
        first_name = new javax.swing.JTextField();
        back_but = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        submit_but1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.blue);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BASIC INFORMATION");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FIRST NAME");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MIDDLE NAME");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LAST NAME");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DAY OF BIRTH");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MONTH OF BIRTH");

        MOB_combo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MOB_combo.setForeground(new java.awt.Color(51, 51, 51));
        MOB_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- ", "January", " February", " March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        MOB_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOB_comboActionPerformed(evt);
            }
        });

        DOB_combo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DOB_combo.setForeground(new java.awt.Color(51, 51, 51));
        DOB_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DOB_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOB_comboActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("(IN BLOCK LETTERS)");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("(IN BLOCK LETTERS)");

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("(IN BLOCK LETTERS)");

        middle_name.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N

        last_name.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N

        first_name.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N

        back_but.setBackground(new java.awt.Color(255, 255, 255));
        back_but.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        back_but.setForeground(java.awt.Color.blue);
        back_but.setText("< BACK");
        back_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_butActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jButton4.setForeground(java.awt.Color.blue);
        jButton4.setText("<< BACK TO HOMEPAGE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        submit_but1.setBackground(new java.awt.Color(255, 255, 255));
        submit_but1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        submit_but1.setForeground(java.awt.Color.blue);
        submit_but1.setText("SUBMIT");
        submit_but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_but1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(151, 151, 151)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(154, 154, 154)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel4)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(85, 85, 85)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(middle_name, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(back_but, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(DOB_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MOB_combo, 0, 264, Short.MAX_VALUE))
                            .addComponent(submit_but1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(549, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(middle_name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(DOB_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(MOB_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(info_pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(back_but, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(submit_but1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(146, 146, 146))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MOB_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOB_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MOB_comboActionPerformed

    private void DOB_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOB_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOB_comboActionPerformed

    private void back_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_butActionPerformed
setVisible(false);
        ack ac=new ack();             // TODO add your handling code here:
ac.setVisible(true);
    }//GEN-LAST:event_back_butActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       welcome w= new welcome();        // TODO add your handling code here:
        setVisible(false);
       
w.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void submit_but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_but1ActionPerformed
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(false);
        
        int db= (int) DOB_combo.getSelectedIndex();
     int mb= (int) MOB_combo.getSelectedIndex();
     if(mb>=1 && mb<=2 )
	{
		if(mb==1 && db>19 && db<=31)
		new second("YOUR ZODIAC STAR IS AQUARIUS. YOU SHOULD HAVE A GARNET LUCKY STONE").setVisible(true);
		else if(mb==2 && db<=18)
		new second("YOUR ZODIAC STAR IS AQUARIUS. YOU SHOULD HAVE A GARNET LUCKY STONE").setVisible(true);		
	}
if(mb>=2 && mb<=3)
	{
		if(mb==2 && db>18 && db<=29)
		new second("YOUR ZODIAC STAR IS PISCES. YOU SHOULD HAVE AN AMETHYST LUCKY STONE").setVisible(true);
		else if(mb==3 && db<=20)
		new second("YOUR ZODIAC STAR IS PISCES. YOU SHOULD HAVE AN AMETHYST LUCKY STONE").setVisible(true);
	}
	if(mb>=3 && mb<=4)
	{
		if(mb==3 && db>20 && db<=31)
		new second("YOUR ZODIAC STAR IS ARIES. YOU SHOULD HAVE A LUCKY BLOOD STONE").setVisible(true);
		else if(mb==4 && db<=19)
		new second("YOUR ZODIAC STAR IS ARIES. YOU SHOULD HAVE A LUCKY BLOOD STONE").setVisible(true);
	}
	if(mb>=4 && mb<=5)
	{
		if(mb==4 && db>19 && db<=30)
		new second("YOUR ZODIAC STAR IS ARIES. YOU SHOULD HAVE A SAPPHIRE LUCKY STONE").setVisible(true);
		else if(mb==5 && db<=20)
		new second("YOUR ZODIAC STAR IS ARIES. YOU SHOULD HAVE A SAPPHIRE LUCKY STONE").setVisible(true);
	}
	if(mb>=5 && mb<=6)
	{
		if(mb==5 && db>20 && db<=31)
		new second("YOUR ZODIAC STAR IS GEMINI. YOU SHOULD HAVE AN AGATE LUCKY STONE").setVisible(true);
		else if(mb==6 && db<=20)
		new second("YOUR ZODIAC STAR IS GEMINI. YOU SHOULD HAVE AN AGATE LUCKY STONE").setVisible(true);
	}
	if(mb>=6 && mb<=7)
	{
		if(mb==6 && db>20 && db<=30)
		new second("YOUR ZODIAC STAR IS CANCER. YOU SHOULD HAVE AN EMARALD LUCKY STONE").setVisible(true);
		else if(mb==7 && db<=22)
		new second("YOUR ZODIAC STAR IS CANCER. YOU SHOULD HAVE AN EMARALD LUCKY STONE").setVisible(true);
	}
	if(mb>=7 && mb<=8)
	{
		if(mb==7 && db>22 && db<=31)
		new second("YOUR ZODIAC STAR IS LEO. YOU SHOULD HAVE AN ONYX LUCKY STONE").setVisible(true);
		else if(mb==8 && db<=22)
		new second("YOUR ZODIAC STAR IS LEO. YOU SHOULD HAVE AN ONYX LUCKY STONE").setVisible(true);
	}
	if(mb>=8 && mb<=9)
	{
		if(mb==8 && db>22 && db<=31)
		new second("YOUR ZODIAC STAR IS VIRGO. YOU SHOULD HAVE A CARNELIAN LUCKY STONE").setVisible(true);
		else if(mb==9 && db<=22)
		new second("YOUR ZODIAC STAR IS VIRGO. YOU SHOULD HAVE A CARNELIAN LUCKY STONE").setVisible(true);
	}
	if(mb>=9 && mb<=10)
	{
		if(mb==9 && db>22 && db<=30)
		new second("YOUR ZODIAC STAR IS LIBRA. YOU SHOULD HAVE A CRYSOLITE LUCKY STONE").setVisible(true);
		else if(mb==10 && db<=22)
		new second("YOUR ZODIAC STAR IS LIBRA. YOU SHOULD HAVE A CRYSOLITE LUCKY STONE").setVisible(true);
	}
	if(mb>=10 && mb<=11)
	{
		if(mb==10 && db>22 && db<=31)
		new second("YOUR ZODIAC STAR IS SCORPIO. YOU SHOULD HAVE A BERYL LUCKY STONE").setVisible(true);
		else if(mb==11 && db<=21)
		new second("YOUR ZODIAC STAR IS SCORPIO. YOU SHOULD HAVE A BERYL LUCKY STONE").setVisible(true);
	}
	if(mb>=11 && mb<=12)
	{
		if(mb==11 && db>21 && db<=30)
		new second("YOUR ZODIAC STAR IS SAGITTARIUS. YOU SHOULD HAVE A CITRINE LUCKY STONE").setVisible(true);
		else if(mb==12 && db<=21)
		new second("YOUR ZODIAC STAR IS SAGITTARIUS. YOU SHOULD HAVE A CITRINE LUCKY STONE").setVisible(true);
	}
	if(mb==12 || mb<=1)
	{
		if(mb==12 && db>22 && db<=31)
		new second("YOUR ZODIAC STAR IS CAPRICORN. YOU SHOULD HAVE A RUBY LUCKY STONE").setVisible(true);
		else if(mb==1 && db<=19)
		new second("YOUR ZODIAC STAR IS CAPRICORN. YOU SHOULD HAVE A RUBY LUCKY STONE").setVisible(true);
	}
        

// TODO add your handling code here:
    }//GEN-LAST:event_submit_but1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(you_basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(you_basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(you_basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(you_basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new you_basic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DOB_combo;
    private javax.swing.JComboBox MOB_combo;
    private javax.swing.JButton back_but;
    private javax.swing.JTextField first_name;
    private javax.swing.JLabel info_pic;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField last_name;
    private javax.swing.JTextField middle_name;
    private javax.swing.JButton submit_but1;
    // End of variables declaration//GEN-END:variables
}
